setwd("/home/lmoffatt/Code/macro_dr/macro_dr/projects/eLife_2025/figures/in_progress/ir_reliability_20260828")
suppressPackageStartupMessages({library(dplyr)})
d <- read.csv("digest/ir_collapse_cells.csv") |> filter(anchor=="sim") |> mutate(S=0.1*z, x=S*nch)
cat("ebar (signed amplitude) quantiles overall:\n"); print(round(quantile(d$ebar, c(0,.05,.25,.5,.75,.95,1)),4))
cat("\nebar by decade of S~N (median, q05, q95):\n")
print(d |> mutate(dec=floor(log10(x))) |> group_by(dec) |>
  summarise(med=round(median(ebar),3), q05=round(quantile(ebar,.05),3), q95=round(quantile(ebar,.95),3), n=n()), n=15)
cat("\n|ebar| envelope check vs a*x^-b: fit on |ebar|>0.02\n")
s <- d |> filter(abs(ebar)>0.02); m <- lm(log10(abs(ebar)) ~ log10(x), data=s)
cat(sprintf("  n=%d  coef: a=%.3f  b=%+.3f  R2=%.3f\n", nrow(s), 10^coef(m)[1], coef(m)[2], summary(m)$r.squared))
cat("\naniso quantiles:\n"); print(round(quantile(d$aniso, c(0,.05,.5,.95,1)),4))
cat("\naniso: violations of 0.25*x^-0.2 with floor 0.045:\n")
v <- d |> filter(aniso > pmax(0.25*x^-0.2, 0.045)); cat("  n viol:", nrow(v), "\n")
print(v |> select(nch,z,interval,aniso) |> head(12), row.names=FALSE)
cat("\nsign of ebar at low S~N (x<1): neg means claimed info EXCEEDS true (bars too small?) check convention\n")
print(d |> filter(x<1) |> count(sign(ebar)))
