setwd("/home/lmoffatt/Code/macro_dr/macro_dr/projects/eLife_2025/figures/in_progress/ir_reliability_20260828")
suppressPackageStartupMessages({library(dplyr);library(tidyr)})
PN <- c("k_on","k_off","i","S","baseline","N_ch")
ci <- read.csv("digest/ir_bias_cis.csv") |> mutate(S=0.1*z, D=interval_in_tau, x=nch*S*sqrt(D),
        sig=(lo>0|hi<0), zp=abs(m)/se, pname=PN[param_index+1])
cell <- ci |> group_by(nch,z,D,x,S) |>
  summarise(babs=max(abs(m)), pabs=pname[which.max(abs(m))], sig_abs=sig[which.max(abs(m))],
            zmax=max(zp), pz=pname[which.max(zp)], sig_z=sig[which.max(zp)], .groups="drop")
cat("which parameter carries the max |bias| (absolute, log10 units):\n"); print(table(cell$pabs))
cat("which parameter carries the max |bias|/SE:\n"); print(table(cell$pz))
cat("\n|bias| absolute quantiles (log10 units):\n"); print(round(quantile(cell$babs, c(0,.5,.9,.99,1)),4))
cat("\nsignificant cells (abs):", sum(cell$sig_abs), "of", nrow(cell), "\n")
s <- cell |> filter(sig_abs)
fit <- function(y, xs, lab){ m <- lm(log10(y) ~ log10(xs)); r <- 10^abs(resid(m))
  cat(sprintf("  %-22s slope %+.3f  R2 %.3f  spread x%.2f\n", lab, coef(m)[2], summary(m)$r.squared, median(r))) }
cat("\nABSOLUTE bias, significant cells only (n=", nrow(s), "):\n", sep="")
fit(s$babs, s$x, "x = N S sqrtD")
fit(s$babs, s$nch, "N alone")
fit(s$babs, s$nch*s$S, "N S")
m3 <- lm(log10(babs) ~ log10(nch)+log10(S)+log10(D), data=s)
cat(sprintf("  free exponents: N %+.3f  S %+.3f  D %+.3f  R2 %.3f\n", coef(m3)[2],coef(m3)[3],coef(m3)[4], summary(m3)$r.squared))
s2 <- cell |> filter(sig_z)
cat("\nbias/SE, significant cells only (n=", nrow(s2), "):\n", sep="")
fit(s2$zmax, s2$x, "x = N S sqrtD"); fit(s2$zmax, s2$nch, "N alone")
m4 <- lm(log10(zmax) ~ log10(nch)+log10(S)+log10(D), data=s2)
cat(sprintf("  free exponents: N %+.3f  S %+.3f  D %+.3f  R2 %.3f\n", coef(m4)[2],coef(m4)[3],coef(m4)[4], summary(m4)$r.squared))
# SE itself: how does the worst-param SE scale? (to understand abs vs relative)
se_cell <- ci |> group_by(nch,z,D,x,S) |> summarise(se_max=max(se), .groups="drop")
m5 <- lm(log10(se_max) ~ log10(nch)+log10(S)+log10(D), data=se_cell)
cat(sprintf("\nSE_max exponents: N %+.3f  S %+.3f  D %+.3f  R2 %.3f\n", coef(m5)[2],coef(m5)[3],coef(m5)[4], summary(m5)$r.squared))
write.csv(cell, "digest/ir_bias_cells.csv", row.names=FALSE)
