# Auto-generated by macroir bootstrap binary writer. Do not edit.
# Reads the flat-doubles binary samples format into a list of 4D arrays.
read_macrodr_bootstrap <- function(path_prefix) {
  manifest <- read.csv(paste0(path_prefix, "_manifest.csv"), stringsAsFactors = FALSE)
  cells    <- read.csv(paste0(path_prefix, "_cells.csv"),    stringsAsFactors = FALSE)
  n_cells <- nrow(cells)
  n_reps  <- if (n_cells > 0) cells$n_replicates[1] else 0
  samples <- list()
  for (i in seq_len(nrow(manifest))) {
    obs <- manifest$observable[i]
    rows <- manifest$rows[i]
    cols <- manifest$cols[i]
    n <- rows * cols * n_reps * n_cells
    bin_path <- paste0(path_prefix, "_", obs, ".bin")
    if (!file.exists(bin_path)) {
      warning(paste0("missing ", bin_path)); next
    }
    flat <- readBin(bin_path, "double", n = n, size = 8)
    samples[[obs]] <- array(flat, dim = c(rows, cols, n_reps, n_cells))
  }
  list(cells = cells, samples = samples, manifest = manifest)
}
