//w/0---
title: "analysis"
author: "Luciano Moffatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

```{r}
Nch=50

fs = 50e3
nsamples= 25
noise=1e-4 *fs/nsamples
```


```{r}
filenames=c(
  "data/figure_1_likelihood_diagnostic_NR",
  "data/figure_1_likelihood_diagnostic_MNR",
  "data/figure_1_likelihood_diagnostic_MNRV",
  "data/figure_1_likelihood_diagnostic_R",
  "data/figure_1_likelihood_diagnostic_MR",
  "data/figure_1_likelihood_diagnostic_MRV",
  "data/figure_1_likelihood_diagnostic_IR",
  "data/figure_1_likelihood_diagnostic_IRV",
  "data/figure_1_simulation"
  
)

algorithms=c("NR"
             ,"MNR"
             ,"MNRV"
             ,"R"
             ,"MR"
             ,"MRV"
             ,"IR"
             ,"IRV"
             ,"SIM")

```


```{r}

d=data.frame()
for (i in 1:length(filenames)){
  
  d0=read.csv(paste0(filenames[i],".csv"), check.names = FALSE) 
  d0$algo=algorithms[i]
  d=rbind(d,d0)
}

```

```{r}
d_MRV=d%>%filter(algo=="MRV", scope=="evolution", value_row==1, is.na(value_col), !is.na(step_start))%>%mutate(component= component_path %>%
           str_replace("^Algo_State_Dynamic\\.", "") %>%
           str_replace("^Patch_State\\.", ""))%>%
  select(sample_index,step_start,step_middle,step_end,component,value_row,value_col,value)%>%pivot_wider(names_from = component, values_from = value)
d_IRV=d%>%filter(algo=="IRV", scope=="evolution", value_row==1,  is.na(value_col), !is.na(step_start))%>%mutate(component= component_path %>%
           str_replace("^Algo_State_Dynamic\\.", "") %>%
           str_replace("^Patch_State\\.", ""))%>%
  select(sample_index,step_start,step_middle,step_end,component,value_row,value_col,value)%>%
  pivot_wider(names_from = component, values_from = value)
#%>%select(step_start,step_middle,step_end)
d_s=d%>%filter(algo=="SIM", scope=="simulation_sub")%>%select(sub_index,sample_index,step_start,step_middle,step_end,component_path,value)%>%pivot_wider(names_from = component_path, values_from = value)
```


```{r}
common_theme = theme_classic()+ theme( legend.position = "right")

compact_theme <- common_theme +theme(
  axis.title.x = element_blank(),
  axis.text.x  = element_blank(),
  axis.ticks.x = element_blank(),
  legend.position = "right",
  plot.margin = margin(1, 5, 1, 5)
)
x_only_ticks=theme(axis.title.x = element_blank(), axis.text.x = element_blank())
y_only_ticks=theme(axis.title.y = element_blank(), axis.text.y = element_blank())
no_y_axis= theme( axis.text.y = element_blank(), # Removes y-axis text
         axis.title.y = element_blank(), # Removes y-axis title
          axis.ticks.y = element_blank(), 
        axis.line.y = element_blank())
no_x_axis= theme( axis.text.x = element_blank(), # Removes y-axis text
         axis.title.x = element_blank(), # Removes y-axis title
          axis.ticks.x = element_blank(), 
        axis.line.x = element_blank())
y_no_title=theme(axis.title.y = element_blank())


xmin=min(d$step_start)
xmax=max(d$step_end)

dx=xmax-xmin
x_scale<-scale_x_continuous(limits = c(xmin-0.05*dx, xmax+0.05*dx))


d_step_IR=0.1
d_step_MR= 0.1
```


```{r}
d_p_IR=0.004*diff(range(-d_s$patch_current/Nch))

```


```{r, fig.height=6,fig.width=12}

MRV_color_plot<- c(
      "current"   = "#009E73",
      "prior"     = "#999999",  # Light Grey
      "posterior" = "#000000",  # Strong Black
      "Markov"    = "#0072B2",  # Deep Blue
      "Markov_on_prior" ="#0072B2",
      "Bayes"     = "#E69F00", 
      "next_measure" ="darkblue"
    )


MRV_bayes_color<-scale_color_manual(
    values =MRV_color_plot,
    breaks = c("current","prior", "posterior","Markov", "Markov_on_prior","Bayes","next_measure"),
    labels = c("Simulated Current","Prior Point State", "Posterior Point State", "Markov Prediction", "Markov Prediction on Prior", "Bayesian Update", "Next Measure")
  ) 

  MRV_bayes_guides<-guides(color = guide_legend(override.aes = list(shape = c(NA,16, 16, NA, NA,NA, NA), 
                                                linetype = c(1,0, 0, 1, 2,1,3))))
 

  IRV_color_plot<- c(
      "current"   = "#009E73",
      "prior"     = "#999999",  # Light Grey
      "prior_state"     = "#999999",  # Light Grey
      "posterior" = "#000000",  # Strong Black
      "posterior_state" ="#000000",
      "Markov"    = "#0072B2",  # Deep Blue
      "Bayes"     = "#E69F00", 
      "next_measure" ="darkblue"
    )


IRV_bayes_color<-scale_color_manual(
    values =IRV_color_plot,
    breaks = c("current","prior", "prior_state","posterior","posterior_state", "Markov", "Bayes", "next_measure"),
    labels = c("Simulated Current","Prior Point State","Prior Boundary State", "Posterior Point State","Posterior Boundary State", "Markov Prediction", "Bayesian Update", "Next Measure")
  ) 

  IRV_bayes_guides<-guides(color = guide_legend(override.aes = list(shape = c(NA,16, NA,16, NA, NA,NA,NA), 
                                                linetype = c(1,0,1, 0, 1, 1,1,3))))
 

  no_legend<-theme(legend.position = "none")
  
(ggplot(d_MRV) +
    
  #0. set the measurment intervals
  geom_vline(aes(xintercept = step_start), linewidth = 1.2, alpha= 0.6, color="grey", linetype=3)+  
  # 1. Current data (Black bars)
  geom_line(data=d_s, aes(x=step_middle, y=-patch_current/Nch, color="current"), 
                linewidth = 0.8) +
# geom_segment(data=d_s, aes(x=step_start, xend=step_end, y=-patch_current/Nch, color="current"), 
#                linewidth = 0.8) +
#    geom_segment(data=d_s, aes(x=step_end, xend=step_end, y=patch_current/-Nch, yend=-lead(patch_current)/-Nch, color="current"), linewidth = 0.8) +
  
  # 2. Auxiliary Markov Path (Dashed/Faint)
  # This represents what the model would predict if it didn't update from data
  geom_segment(aes(x = step_start + d_step_IR * (step_end - step_start), 
                   y = lag(P_mean_t2_y1),
                   xend = step_end - d_step_IR * (step_end - step_start), 
                   yend = P_mean_t2_y0, color="Markov_on_prior"), 
                alpha = 0.6, linetype = "dashed",linewidth = 0.8,
               arrow = arrow(length = unit(0.070, "in"))) +

  # 3. Main Markov Prediction Path (Solid Blue)
  geom_segment(aes(x = step_start + d_step_IR * (step_end - step_start), 
                   y = P_mean_t1_y1,
                   xend = step_end - d_step_IR * (step_end - step_start), 
                   yend = P_mean_t2_y1, color = "Markov"), 
               linewidth = 1, arrow = arrow(length = unit(0.070, "in"))) +

  # 4. Bayesian Update Arrows (Gold)
  # We make these slightly thicker to show the 'work' the data is doing
  geom_segment(aes(x = step_start + d_step_IR * (step_end - step_start), 
                   y = lag(P_mean_t2_y1),
                   xend = step_start + d_step_IR * (step_end - step_start), 
                   yend = P_mean_t1_y1, color = "Bayes"), 
               linewidth = 1, arrow = arrow(length = unit(0.070, "in"))) +

  # 5. Connecting Markov Step (Horizontal transition)
  geom_segment(aes(x = step_end - d_step_IR * (step_end - step_start), 
                   y = P_mean_t2_y1,
                   xend = lead(step_start) + d_step_IR * (lead(step_end) - lead(step_start)), 
                   yend = P_mean_t2_y1, color="next_measure"),linetype = 3,  
               linewidth = 0.5) +

  # 6. Points (Last layer so they sit on top of the arrows)
  geom_point(aes(x = step_start + d_step_IR * (step_end - step_start), y = lag(P_mean_t2_y1), color = "prior"), size = 2) +
  geom_point(aes(x = step_end - d_step_IR * (step_end - step_start), y = P_mean_t2_y0, color = "prior"), alpha = 0.6, size = 2) +
  geom_point(aes(x = step_start + d_step_IR * (step_end - step_start), y = P_mean_t1_y1, color = "posterior"), size = 2) +
  geom_point(aes(x = step_end - d_step_IR * (step_end - step_start), y = P_mean_t2_y1, color = "posterior"), size = 2) +

  # --- Scales and Themes ---
  x_scale +
  common_theme +
  ylab("open state\nprobability") +
   MRV_bayes_color+MRV_bayes_guides +theme(legend.position = "inside",legend.position.inside = c(0.8,0.2), legend.title = element_blank()))+

(
  ggplot(d_IRV) +
  geom_vline(aes(xintercept = step_start), linewidth = 1.2, alpha= 0.6, color="grey", linetype=3)+  
    # 1. Background Data
   geom_line(data=d_s, aes(x=step_middle, y=-patch_current/Nch, color="current"), 
                linewidth = 0.8) +
# geom_segment(data=d_s, aes(x=step_start, xend=step_end, y=-patch_current/Nch, color="current"), 
 #               linewidth = 0.8) +
#    geom_segment(data=d_s, aes(x=step_end, xend=step_end, y=patch_current/-Nch, yend=-lead(patch_current)/-Nch, color="current"), linewidth = 0.8) +
   
    # 2. Prior Points (Smaller)
    geom_point(aes(x=step_start+d_step_IR*(step_end-step_start), y=lag(P_mean_t20_y1), color="prior"), size = 2) +
  #  geom_point(aes(x=step_end-d_step_IR*(step_end-step_start), y=P_mean_t11_y0, color="prior"), size = 2) +
    
    # 3. Posterior Points (Larger)
  #  geom_point(aes(x=step_start+d_step_IR*(step_end-step_start), y=P_mean_t10_y1, color="posterior"), size = 2) +
    geom_point(aes(x=step_end-d_step_IR*(step_end-step_start), y=P_mean_t20_y1, color="posterior"), size = 2) +
    
    # 4. Bayesian Update Arrows (Thicker Gold)
    geom_segment(aes(x=step_start+d_step_IR*(step_end-step_start), y=lag(P_mean_t20_y1),
                     xend=step_start+d_step_IR*(step_end-step_start), yend=P_mean_t10_y1, color="Bayes"), 
                 linewidth = 0.7, arrow=arrow(length=unit(0.07,"in"))) +
    
    # Intermediate Bayesian Arrows
    geom_segment(aes(x=(step_start+d_step_IR*(step_end-step_start))*0.75 + (step_end-d_step_IR*(step_end-step_start))*0.25, 
                     y=lag(P_mean_t20_y1)*0.75 + P_mean_t11_y0*0.25,
                     xend=(step_start+d_step_IR*(step_end-step_start))*0.75 + (step_end-d_step_IR*(step_end-step_start))*0.25,
                     yend=P_mean_t10_y1*0.75 + P_mean_t20_y1*0.25, color="Bayes"), 
                 alpha=0.5, linewidth = 0.7, arrow=arrow(length=unit(0.05,"in"))) +
    
    geom_segment(aes(x=(step_start+d_step_IR*(step_end-step_start))*0.5 + (step_end-d_step_IR*(step_end-step_start))*0.5, 
                     y=lag(P_mean_t20_y1)*0.5 + P_mean_t11_y0*0.5,
                     xend=(step_start+d_step_IR*(step_end-step_start))*0.5 + (step_end-d_step_IR*(step_end-step_start))*0.5,
                     yend=P_mean_t10_y1*0.5 + P_mean_t20_y1*0.5, color="Bayes"), 
                 alpha=0.5, linewidth = 0.7, arrow=arrow(length=unit(0.05,"in"))) +
    
    geom_segment(aes(x=(step_start+d_step_IR*(step_end-step_start))*0.25 + (step_end-d_step_IR*(step_end-step_start))*0.75, 
                     y=lag(P_mean_t20_y1)*0.25 + P_mean_t11_y0*0.75,
                     xend=(step_start+d_step_IR*(step_end-step_start))*0.25 + (step_end-d_step_IR*(step_end-step_start))*0.75,
                     yend=P_mean_t10_y1*0.25 + P_mean_t20_y1*0.75, color="Bayes"), 
                 alpha=0.5, linewidth = 0.7, arrow=arrow(length=unit(0.05,"in"))) +
    
    geom_segment(aes(x=step_end-d_step_IR*(step_end-step_start), y=P_mean_t11_y0, 
                     xend=step_end-d_step_IR*(step_end-step_start), yend=P_mean_t20_y1, color="Bayes"), 
                 linewidth = 1, arrow=arrow(length=unit(0.07,"in"))) +

    # 5. Markov and Posterior Connections
    geom_segment(aes(x=step_start+d_step_IR*(step_end-step_start), y=P_mean_t10_y1,
                     xend=step_end-d_step_IR*(step_end-step_start), yend=P_mean_t20_y1, color="posterior_state"), alpha=1, linewidth = 1) +
    
    geom_segment(aes(x=step_start+d_step_IR*(step_end-step_start), y=lag(P_mean_t20_y1)+d_p_IR,
                     xend=step_end-d_step_IR*(step_end-step_start), yend=P_mean_t11_y0+d_p_IR, color="prior_state"), 
                 linewidth = 1) +
    geom_segment(aes(x=step_start+d_step_IR*(step_end-step_start), y=lag(P_mean_t20_y1)-d_p_IR*2,
                     xend=step_end-d_step_IR*(step_end-step_start), yend=P_mean_t11_y0-d_p_IR*2, color="Markov"), 
                 linewidth = 0.5, arrow=arrow(length=unit(0.07,"in"))) +

    geom_segment(aes(x=step_end-d_step_IR*(step_end-step_start), y=P_mean_t20_y1,
                     xend=lead(step_start)+ d_step_IR*(lead(step_end)-lead(step_start)), yend=P_mean_t20_y1, color="next_measure"),linetype = 3, 
                 linewidth = 0.5) +
    
    # --- Scales and Themes ---
    x_scale +
    common_theme + no_y_axis + IRV_bayes_color+IRV_bayes_guides+theme(legend.position = "inside",legend.position.inside = c(0.8,0.2), legend.title = element_blank())
)
  ggsave("Figure_1.pdf")
```


```{r}
s_MRV=d%>%filter(algo=="MRV", scope=="evolution", !is.na(step_start))%>%mutate(component= component_path %>%
           str_replace("^Algo_State_Dynamic\\.", "") %>%
           str_replace("^Patch_State\\.", ""))%>%
  select(sample_index,step_start,step_middle,step_end,component,value_row,value_col,value)%>%pivot_wider(names_from =c( component,value_row,value_col), values_from = value)
```


```{r}
s_IRV=d%>%filter(algo=="IRV",  scope=="evolution", !is.na(step_start))%>%mutate(component= component_path %>%
           str_replace("^Algo_State_Dynamic\\.", "") %>%
           str_replace("^Patch_State\\.", ""))%>%
  select(sample_index,step_start,step_middle,step_end,component,value_row,value_col,value)%>%pivot_wider(names_from =c( component,value_row,value_col), values_from = value)
#%>%select(step_start,step_middle,step_end)
```




```{r}
s_IRV%>%mutate(m_0_y0=lag(P_mean_t20_y1_1_NA),
               s_0_y0=lag(P_Cov_t20_y1_1_1)/Nch, 
               m_1_y0= P_mean_t11_y0_1_NA,  
               s_1_y0=P_Cov_t11_y0_1_1/Nch,
               s_01_y0=P_cross_cov_0t_y0_1_1/Nch,
               m_0_y1=P_mean_t10_y1_1_NA, 
               s_0_y1=P_Cov_t10_y1_1_1/Nch, 
               m_1_y1=P_mean_t20_y1_1_NA, 
               s_1_y1=P_Cov_t20_y1_1_1/Nch,
               s_01_y1=P_cross_cov_0t_y1_1_1/Nch)->ss_IRV
```


```{r}
s_MRV%>%mutate(m_0_y0=lag(P_mean_t2_y1_1_NA),
               s_0_y0=lag(P_Cov_t2_y1_1_1)/Nch, 
               m_1_y0= P_mean_t2_y0_1_NA,  
               s_1_y0=P_Cov_t2_y0_1_1/Nch,
               s_01_y0=P_cross_cov_0t_y0_1_1/Nch,
              
                m_0_y1=P_mean_t1_y1_1_NA, 
               s_0_y1=P_Cov_t1_y1_1_1/Nch, 
               m_1_y1=P_mean_t2_y1_1_NA, 
               s_1_y1=P_Cov_t2_y1_1_1/Nch,
               s_01_y1=P_cross_cov_0t_y1_1_1/Nch)->ss_MRV




```





```{r}
library(ggplot2)
library(ellipse)

# --- 1. Helper Function ---
# Generates a data frame for an ellipse given Mean and Covariance
get_ellipse_df <- function(data, x, y, sxx, sxy, syy,..., level = 0.95) {
  data %>%
    # Drop rows where any of the required math inputs are NA
    filter(!is.na({{x}}), !is.na({{y}}), 
           !is.na({{sxx}}), !is.na({{sxy}}), !is.na({{syy}})) %>%
    mutate(ellipse_coords = pmap(list({{x}}, {{y}}, {{sxx}}, {{sxy}}, {{syy}}), 
      function(cur_x, cur_y, cur_sxx, cur_sxy, cur_syy) {
        
        # Build the matrix
        sigma <- matrix(c(cur_sxx, cur_sxy, cur_sxy, cur_syy), nrow = 2)
        mu <- c(cur_x, cur_y)
        
        # Calculate ellipse
        coords <- ellipse::ellipse(sigma, centre = mu, level = level, npoints = 100)
        as_tibble(coords)
      }
    )) %>%
    unnest(ellipse_coords) %>%
    select(..., x, y)
}
```


```{r}
MRV_prior= get_ellipse_df(data= ss_MRV, x= m_0_y0, y= m_1_y0,sxx = s_0_y0, sxy = s_01_y0, syy=s_1_y0,sample_index,level = 0.95)%>%mutate(algo="MRV")
MRV_posterior= get_ellipse_df(data= ss_MRV, x= m_0_y1, y= m_1_y1,sxx = s_0_y1, sxy = s_01_y1, syy=s_1_y1,sample_index,level = 0.95)%>%mutate(algo="MRV")

IRV_prior= get_ellipse_df(data= ss_IRV, x= m_0_y0, y= m_1_y0,sxx = s_0_y0, sxy = s_01_y0, syy=s_1_y0,sample_index,level = 0.95)%>%mutate(algo="IRV")
IRV_posterior= get_ellipse_df(data= ss_IRV, x= m_0_y1, y= m_1_y1,sxx = s_0_y1, sxy = s_01_y1, syy=s_1_y1,sample_index,level = 0.95)%>%mutate(algo="IRV")
```


```{r}
# --- 4. Plot with ggplot ---
ggplot(MRV_prior)  + geom_path(aes(x = x, y = y, color = "prior", group = sample_index)) +geom_path(data = MRV_posterior,aes(x = x, y = y, color = "posterior", group = sample_index)) +
geom_path(data=IRV_prior,aes(x = x, y = y, color = "prior", group = sample_index)) +geom_path(data=IRV_posterior,aes(x = x, y = y, color = "posterior", group = sample_index))+facet_grid(~algo)+coord_fixed()


```


```{r}
# A. The Ellipses (95% Confidence Regions)
  geom_polygon(alpha = 0.2) + # Filled region
  geom_path(linewidth = 1) +  # Outline
  
  # B. The Means (Center points)
  geom_point(data = centers_MRV, size = 3) +
  
  # C. Styling
  scale_color_manual(values = c("Prior" = "#E69F00", "Posterior" = "#56B4E9")) +
  scale_fill_manual(values = c("Prior" = "#E69F00", "Posterior" = "#56B4E9")) +
  coord_fixed() + # Keeps the geometry true
  theme_minimal() +
  labs(title = "MacroMR Update: Prior vs. Posterior",
       subtitle = "95% Probability Regions",
       x = "start probability state",
       y = "end probability state")
  )+
  (ggplot(plot_data_IRV, aes(x = x, y = y, color = Type, fill = Type)) +
  
  # A. The Ellipses (95% Confidence Regions)
  geom_polygon(alpha = 0.2) + # Filled region
  geom_path(linewidth = 1) +  # Outline
  
  # B. The Means (Center points)
  geom_point(data = centers_IRV, size = 3) +
  
  # C. Styling
  scale_color_manual(values = c("Prior" = "#E69F00", "Posterior" = "#56B4E9")) +
  scale_fill_manual(values = c("Prior" = "#E69F00", "Posterior" = "#56B4E9")) +
  coord_fixed() + # Keeps the geometry true
  theme_minimal() +
  labs(title = "MacroIR Updeate: Prior vs. Posterior",
       subtitle = "95% Probability Regions",
        x = "start probability state",
       y = "end probability state")
  )
  
```

```{r}

i_step=2
gmean_ij_0_0=d_IRV$gmean_ij_0_0[i_step]
gmean_ij_0_1=d_IRV$gmean_ij_0_1[i_step]
gmean_ij_1_0=d_IRV$gmean_ij_1_0[i_step]
gmean_ij_1_1=d_IRV$gmean_ij_1_1[i_step]

gvar_i_0=d_IRV$gvar_i_0[i_step]
gvar_i_1=d_IRV$gvar_i_0[i_step]

yobs= d_IRV$patch_current[i_step]

dp=data.frame(N0=0:Nch)%>%mutate(p0_0 = (Nch- N0)/Nch, p0_1=N0/Nch)%>%
  cross_join(data.frame(N1=0:Nch)%>%mutate(p1_0 = (Nch- N1)/Nch, p1_1=N1/Nch))
dp<-dp%>%mutate(yfit= Nch*(gmean_ij_0_0*p0_0+gmean_ij_0_1*p0_1+gmean_ij_1_0*p1_0+gmean_ij_1_1*p1_1))%>%
         mutate(yvar= Nch*(gvar_i_0*p0_0+gvar_i_1*p0_1)+noise)%>%
         mutate(logLik= 0.5*(log(2 * pi * yvar)-(yfit-yobs)^2/yvar ))

dp
 








```
