<program>         ::= <statement> ( <newline> <statement> )* <newline>*

<statement>       ::= <comment>
                    | <assignment>
                    | <function_call>
                    | <identifier>
                    | <literal>
                    | <string_literal>
                    | <argument_list>
                    | <vector_literal>
                    | <tuple_literal>

<comment>         ::= "//" <comment_text>

<assignment>      ::= <identifier> <ws>* "=" <ws>* <expression>

<function_call>   ::= <identifier> "(" <wsline>* <argument_list>? <wsline>* ")"

<argument_list>   ::= <argument> ( <wsline>* "," <wsline>* <argument> )*

<argument>        ::= <assignment>
                    | <expression>

<expression>      ::= <literal>
                    | <string_literal>
                    | <identifier>
                    | <function_call>
                    | <argument_list>
                    | <vector_literal>
                    | <tuple_literal>

<vector_literal>  ::= "[" <wsline>* <expression_list>? <wsline>* "]"

<tuple_literal>   ::= "{" <wsline>* <expression_list>? <wsline>* "}"

<expression_list> ::= <expression> ( <wsline>* "," <wsline>* <expression> )*

<literal>         ::= <number>
<number>          ::= <sign>? <unsigned_number> <exponent_part>?
<unsigned_number> ::= <digits> ( "." <digits> )?
<exponent_part>   ::= ( "E" | "e" ) <sign>? <digits>
<sign>            ::= "+" | "-"

<string_literal>  ::= <double_quoted_string>
                    | <single_quoted_string>

<double_quoted_string> ::= "\"" <double_quoted_char>* "\""
<single_quoted_string> ::= "'" <single_quoted_char>* "'"

<identifier>      ::= <identifier_start> <identifier_char>*
<identifier_start>::= [a-zA-Z_]
<identifier_char> ::= [a-zA-Z0-9_]

<digits>          ::= [0-9]+
<newline>         ::= "\n"
<ws>              ::= " " | "\t"
<wsline>          ::= <ws> | <newline>
